# Generated by Django 4.0.6 on 2022-07-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_playdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playdate',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='playdate',
            name='date',
            field=models.DateField(default=1, verbose_name='Dates you played'),
            preserve_default=False,
        ),
    ]
