# Generated by Django 4.0.6 on 2022-07-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_game_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='desc',
            new_name='description',
        ),
    ]
