# Generated by Django 4.0.6 on 2022-07-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_desc_game_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='description',
            new_name='desc',
        ),
    ]
